### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by arpitjindal97** [xgfone/bt#6]
I have created a tracker (udp server). My actual code for this service is very small and have mostly used the sample code.

After running the pod for around 7 days. I see memory usage keeps increasing as it processes the requests. When I restart the pod the memory falls back to 2 MB or 3 MB which is expected for this type of small app.

Screenshot from grafana featuring both old and new pod:
<img width="696" alt="Screen Shot 2022-08-26 at 21 13 47" src="https://user-images.githubusercontent.com/15676216/186943534-51a61ae9-e478-47d8-836c-e00ff45f810b.png">

While typing this message itself. Memory has increased from 1.2 MB to 5 MB. I guess, there is some variable in the underlying library that is misbehaving or escaping from garbage cleanup.

```
package tracker

import (
	"bytes"
	"encoding/json"
	"example.com/m/internal/pkg/utils"
	"github.com/xgfone/bt/metainfo"
	"github.com/xgfone/bt/tracker/udptracker"
	"net"
	"net/http"
)

var OtherTrackers []string

func UDPTrackerServer(sconn net.PacketConn) {
	server := udptracker.NewServer(sconn, testHandler{})
	defer server.Close()
	server.Run()
}

type testHandler struct{}

func (testHandler) OnConnect(raddr *net.UDPAddr) (err error) { return }

func (testHandler) OnAnnounce(raddr *net.UDPAddr, req udptracker.AnnounceRequest) (r udptracker.AnnounceResponse, err error) {
	go addTorrent(req.InfoHash.String())
	RedisAdd(req.InfoHash.String(), req.Left, raddr.IP, req.Port)
	r = udptracker.AnnounceResponse{
		Interval:  120, // 2 mins
		Leechers:  uint32(int(RedisCount(req.InfoHash.String() + ":incomplete"))),
		Seeders:   uint32(int(RedisCount(req.InfoHash.String() + ":complete"))),
		Addresses: utils.GetPeersFromTrackers(req.PeerID, req.InfoHash, OtherTrackers, RedisGet(req.InfoHash.String())),
	}
	return
}
func (testHandler) OnScrap(raddr *net.UDPAddr, infohashes []metainfo.Hash) (
	rs []udptracker.ScrapeResponse, err error) {
	rs = make([]udptracker.ScrapeResponse, len(infohashes))
	for i := range infohashes {
		rs[i] = udptracker.ScrapeResponse{
			Seeders:   uint32(int(RedisCount(infohashes[i].String() + ":complete"))),
			Leechers:  uint32(int(RedisCount(infohashes[i].String() + ":incomplete"))),
			Completed: uint32(int(RedisCount(infohashes[i].String() + ":complete"))),
		}
	}
	return
}

var APIServerURL string

func addTorrent(infohash string) {
	reqBody, _ := json.Marshal(map[string]string{
		"infohash": infohash,
	})

	_, _ = http.Post(APIServerURL+"/torrents", "application/json", bytes.NewBuffer(reqBody))
}
```

I'm using Redis to store the peer data and I don't think that should be an issue

**Comment by xgfone** [comment]
Got, it will check it.

**Comment by xgfone** [comment]
```go
func addTorrent(infohash string) {
	reqBody, _ := json.Marshal(map[string]string{
		"infohash": infohash,
	})

	_, _ = http.Post(APIServerURL+"/torrents", "application/json", bytes.NewBuffer(reqBody))
}
```
Here is memory leak, see `_, _ = http.Post(APIServerURL+"/torrents", "application/json", bytes.NewBuffer(reqBody))`. `http.Post` returns a `*http.Response`, and you must call `http.Response.Body.Close()`. Or, it will lead to memory lead because the http connection is not closed.

**Comment by arpitjindal97** [comment]
Awesome dude. Thanks for the fix

It's been an hour and memory is not going beyond 5 MB.
